name: deploy

on:
  push:
    branches:
      - main
      - release/prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: aws login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 1.2.2

      - if: ${{ github.ref == 'refs/heads/main' }}
        run: ENVIRONMENT_NAME='dev'

      - if: ${{ github.ref == 'refs/heads/release/prd' }}
        run: ENVIRONMENT_NAME='prd'

      - name: exec commands
        run: |
          cd envs/${ENVIRONMENT_NAME}/
          terraform init --upgrade
          terraform plan
          terraform apply --auto-approve
